### ISSUE TITLE
not able to customize chart using css

### ISSUE THREAD

**Issue by Suraj-Naik1** [HanSolo/smoothcharts#3]

**Comment by HanSolo** [comment]
Yep that's possible, it was never really made for customizing it via css but for using code

**Comment by Suraj-Naik1** [comment]
Can it be overridden somehow so that we can use css to customize?

**Comment by Suraj-Naik1** [comment]
I was not able to edit the legend shape.

**Comment by HanSolo** [comment]
Well you can create a class that extends Region. This class you can give a style which can contain a -fx-shape element that contains whatever svg path you have on your mind. The you have to get the LegendItems from the Legend and there you can set your own symbol by calling legendNode.setSymbol(INSTANCE_OF_YOUR_REGION). Did a quick test with that approach and it seems to work.

**Comment by Suraj-Naik1** [comment]
Thank you for the help
